"""table Applicant added

Revision ID: f4f7cd112799
Revises: 
Create Date: 2022-03-28 20:53:52.019220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4f7cd112799'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applicant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('applicant_name', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.Column('district', sa.String(length=50), nullable=True),
    sa.Column('zip_code', sa.String(length=10), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('street', sa.String(length=100), nullable=True),
    sa.Column('building', sa.String(length=20), nullable=False),
    sa.Column('room', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('letter', 'date_of_issue',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('letter', 'expiry_date',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.create_unique_constraint(None, 'letter', ['lc_number'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'letter', type_='unique')
    op.alter_column('letter', 'expiry_date',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('letter', 'date_of_issue',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.drop_table('applicant')
    # ### end Alembic commands ###
